import React, { useMemo, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from "react-native";
import { Provider as PaperProvider, Checkbox } from "react-native-paper";
import * as DocumentPicker from "expo-document-picker";
import { Ionicons } from "@expo/vector-icons";

const LATIN_INFO_POINTS = [
  "Consent Form – will be generated by the system.",
  "Printed Copy of Grades from the Portal – automatically generated (no upload needed).",
  "Certificate of Good Moral Character – upload below.",
  "Certificate of OJT Completion – upload below.",
  "Barangay Clearance – upload below.",
];

const LATIN_UPLOAD_ITEMS = [
  { key: "goodMoral", label: "Certificate of Good Moral Character", required: true },
  { key: "ojtCompletion", label: "Certificate of OJT Completion", required: true },
  { key: "barangayClearance", label: "Barangay Clearance", required: true },
];

const ApplicationForLatinHonor = () => {
  const [requirements, setRequirements] = useState(() => {
    const initial = {};
    LATIN_UPLOAD_ITEMS.forEach((item) => {
      initial[item.key] = { file: null, toFollow: false };
    });
    return initial;
  });
  const [consentGenerated, setConsentGenerated] = useState(false);

  const handleUpload = async (key) => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: ["application/pdf", "image/*"],
        copyToCacheDirectory: true,
      });
      if (result.type === "cancel") return;
      const file = result.assets ? result.assets[0] : result;
      setRequirements((prev) => ({
        ...prev,
        [key]: { ...prev[key], file, toFollow: false },
      }));
    } catch (error) {
      console.warn("Upload error:", error);
    }
  };

  const toggleFollow = (key) => {
    setRequirements((prev) => ({
      ...prev,
      [key]: {
        ...prev[key],
        toFollow: !prev[key].toFollow,
        file: prev[key].toFollow ? prev[key].file : null,
      },
    }));
  };

  const handleGenerateConsent = () => {
    setConsentGenerated(true);
  };

  const requirementCards = useMemo(
    () =>
      LATIN_UPLOAD_ITEMS.map((item) => {
        const data = requirements[item.key];
        return (
          <View key={item.key} style={styles.requirementCard}>
            <Text style={styles.requirementTitle}>
              {item.label} <Text style={styles.required}>*</Text>
            </Text>
            <Text style={styles.requirementHint}>PDF or Image (JPG/PNG)</Text>
            <TouchableOpacity
              style={styles.uploadInput}
              onPress={() => handleUpload(item.key)}
              disabled={data.toFollow}
            >
              <Text style={styles.uploadButtonText}>Choose File</Text>
              <Text style={styles.fileName}>
                {data.file?.name || "No file chosen"}
              </Text>
            </TouchableOpacity>
            <View style={styles.followRow}>
              <Checkbox
                status={data.toFollow ? "checked" : "unchecked"}
                onPress={() => toggleFollow(item.key)}
                color="#1d4ed8"
              />
              <Text style={styles.followText}>Mark as To Follow</Text>
            </View>
          </View>
        );
      }),
    [requirements]
  );

  return (
    <PaperProvider>
      <ScrollView style={styles.screen}>
        <View style={styles.infoCard}>
          <View style={styles.infoHeader}>
            <Text style={styles.infoHeaderText}>Latin Honors Requirements</Text>
          </View>
          <View style={styles.infoBody}>
            {LATIN_INFO_POINTS.map((point, index) => (
              <View key={index} style={styles.infoRow}>
                <View style={styles.infoBullet} />
                <Text style={styles.infoText}>{point}</Text>
              </View>
            ))}
            <Text style={styles.infoNote}>
              Make sure all uploaded files are clear and readable. Accepted formats: PDF, JPG, PNG.
            </Text>
          </View>
        </View>

        <View style={styles.consentCard}>
          <View style={styles.consentText}>
            <Text style={styles.consentTitle}>Consent Form & Printed Copy of Grades</Text>
            <Text style={styles.consentSubtitle}>
              The system will generate your Consent Form and Report of Grades automatically.
              No upload required here, just tap Generate Consent.
            </Text>
          </View>
          <TouchableOpacity style={styles.consentButton} onPress={handleGenerateConsent}>
            <Ionicons name="document-text-outline" size={16} color="#2563eb" />
            <Text style={styles.consentButtonText}>Generate Consent</Text>
          </TouchableOpacity>
        </View>
        <View
          style={[
            styles.consentStatus,
            consentGenerated ? styles.consentStatusSuccess : styles.consentStatusPending,
          ]}
        >
          <Ionicons
            name={consentGenerated ? "checkmark-circle" : "alert-circle"}
            size={16}
            color={consentGenerated ? "#15803d" : "#b45309"}
          />
          <Text
            style={[
              styles.consentStatusText,
              consentGenerated ? styles.consentStatusTextSuccess : styles.consentStatusTextPending,
            ]}
          >
            {consentGenerated
              ? "Consent generated – tap again to regenerate."
              : "Consent not generated yet."}
          </Text>
        </View>

        <View style={styles.requirementGrid}>{requirementCards}</View>

        <TouchableOpacity style={styles.saveButton}>
          <Ionicons name="save-outline" size={18} color="#fff" />
          <Text style={styles.saveButtonText}>Save Requirements</Text>
        </TouchableOpacity>
      </ScrollView>
    </PaperProvider>
  );
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f6f6f6",
    padding: 16,
  },
  infoCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#c7d2fe",
    marginBottom: 16,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  infoHeader: {
    backgroundColor: "#1d4ed8",
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  infoHeaderText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  infoBody: {
    padding: 16,
    backgroundColor: "#eff6ff",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  infoBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#1d4ed8",
    marginTop: 6,
    marginRight: 10,
  },
  infoText: {
    flex: 1,
    color: "#1f2937",
    fontSize: 13,
  },
  infoNote: {
    marginTop: 8,
    fontSize: 12,
    color: "#4b5563",
  },
  consentCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  consentText: {
    flex: 1,
    marginRight: 12,
  },
  consentTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  consentSubtitle: {
    fontSize: 12,
    color: "#4b5563",
    marginTop: 4,
  },
  consentButton: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 6,
  },
  consentButtonText: {
    color: "#2563eb",
    fontWeight: "700",
  },
  consentStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignSelf: "flex-start",
    marginTop: 12,
    marginBottom: 12,
  },
  consentStatusSuccess: {
    backgroundColor: "#dcfce7",
  },
  consentStatusPending: {
    backgroundColor: "#fef3c7",
  },
  consentStatusText: {
    fontSize: 13,
    fontWeight: "600",
  },
  consentStatusTextSuccess: {
    color: "#15803d",
  },
  consentStatusTextPending: {
    color: "#b45309",
  },
  requirementGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 4,
  },
  requirementCard: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#fff",
  },
  requirementTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  required: {
    color: "#dc2626",
  },
  requirementHint: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 4,
  },
  uploadInput: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: "#f9fafb",
  },
  uploadButtonText: {
    color: "#1d4ed8",
    fontWeight: "600",
  },
  fileName: {
    marginTop: 6,
    fontSize: 12,
    color: "#374151",
  },
  followRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  followText: {
    color: "#1f2937",
    fontWeight: "500",
  },
  saveButton: {
    marginTop: 16,
    backgroundColor: "#1d4ed8",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
});

export default ApplicationForLatinHonor;
